mac-s-g/react-json-view

Dockerfile, docker/server.sh, entrypoints/server.sh, package.json, src/html/index.html.template, src/js/components/PrettyJson.js, src/js/components/PrettyObject.js, src/js/entry.js, src/js/helpers/util.js, src/style/_variables.scss, src/style/app-globals.scss, webpack.config.js
stable first version:
how-to example
result:
=> first stable version

example/example.js
=> Doc updates

src/js/components/JsonObject.js, src/js/index.js, src/style/app-globals.scss
'root' display name was missing from json root
=> Root name missing

src/js/components/DataTypes/Array.js, src/js/components/DataTypes/Boolean.js, src/js/components/DataTypes/Function.js, src/js/components/DataTypes/Nan.js, src/js/components/DataTypes/Null.js, src/js/components/DataTypes/Number.js, src/js/components/DataTypes/Object.js, src/js/components/DataTypes/String.js, src/js/components/JsonViewer.js
broke different components into their own files
=> updated file organization

src/js/components/DataTypes/DataTypes.js, src/js/components/DataTypes/Object.js
=> Data type components

README.md, example/example.js, package.json, src/js/components/DataTypes/Object.js, src/js/components/JsonViewer.js, src/js/index.js, src/js/stores/ObjectAttributes.js, src/style/_variables.scss, src/style/app-globals.scss
exposed the following props:
name, collapsed and indentWidth
=> added persistent updates and some style updates

docker/build.sh, example/example.js, src/js/components/DataTypes/Boolean.js, src/js/components/DataTypes/DataTypeLabel.js, src/js/components/DataTypes/Float.js, src/js/components/DataTypes/Function.js, src/js/components/DataTypes/Integer.js, src/js/components/DataTypes/Object.js, src/js/components/DataTypes/String.js, src/js/components/VariableMeta.js, src/js/index.js, src/js/stores/ConfigStore.js, src/style/_variables.scss, src/style/variable_meta.scss
added displayDataTypes, displayObjectSize and enableClipboard app props
=> New features

package.json, src/js/components/AddKeyRequest.js, src/js/components/DataTypes/Object.js, src/js/components/VariableEditor.js, src/js/components/VariableMeta.js, src/js/components/icons.js
removed react-icons warnings by removing react-icons dependency!
=> Resolve react icons warning

README.md, example/example.js, package.json, src/js/components/DataTypes/Object.js
=> allow null or false for component name

example/example.js, package.json, src/js/components/DataTypes/Function.js, src/js/components/DataTypes/String.js, src/js/components/VariableEditor.js, src/js/components/VariableMeta.js, src/js/components/icons.js, src/js/helpers/parseInput.js, src/js/helpers/stringifyVariable.js, src/js/themes/getStyle.js, test/tests/js/components/DataTypes/Function-test.js, test/tests/js/components/VariableEditor-test.js, test/tests/js/components/icons-test.js, test/tests/js/helpers/parseInput-test.js, test/tests/js/helpers/stringifyVariable-test.js
clear input value when opening edit box
=> Edit value

package.json, src/js/components/VariableEditor.js, src/js/components/VariableMeta.js
performance investigation inspired by #92
=> removed react-tooltip because performance was not good

.babelrc, entrypoints/install-test-dependencies.sh, package.json, src/js/components/DataTypes/Object.js, src/js/components/VariableEditor.js, src/js/index.js, webpack.config.js
=> updated dependencies, removed unused dependencies, optimized build

package.json, src/js/components/VariableEditor.js
added some UX improvements including:
* double click value to enter edit mode
* escape key exits edit mode
* ctrl+enter submits edit form
=> Gui propositions 91

src/js/components/DataTypes/Object.js
removed state assignemnt for react-16 support
#107
=> react 16 warning resolution

README.md
=> Added syntax highlighting hints

README.md
fixed incorrect docs as noted by @liester on issue #140
=> updated incorrect doc

docker/README.md
migrating docs from #135 issue to README
=> Docker readme

README.md
adding link from main readme to docker readme.
=> linking to docker docs

package.json
open dev server automatically when running `npm run dev:hot`
=> open dev server automatically

README.md, demo/src/js/components/Demo.js, src/js/components/VariableEditor.js
=> Allow Cmd+Enter to submit, Cmd+Click to edit

index.d.ts
=> Added TypeScript definitions.

index.d.ts
=> Update index.d.ts to add `declare` modifier.

README.md
Adding missing default sortObjects prop
=> fix sort docs

package.json
Adds React 17 to the peer dependencies as React 17 has no actual impact on this package
=> Adds support for React 17

package-lock.json, package.json
i'm really not sure why it's there...
=> remove node dependency

package-lock.json, package.json
=> upgrading flux to 4.0.1

package.json
new patch version will include #322 (don't sort array keys)
=> bump patch to 1.20.5

package.json
1.21.0 includes support for `displayArrayKey` prop.
=> bump minor version (1.21)

dev-server/src/index.js, package-lock.json, package.json, src/js/components/VariableEditor.js
=> quotesOnKeys bugfix

package-lock.json, package.json, src/js/components/VariableEditor.js, src/js/themes/getStyle.js, src/js/themes/styleConstants.js
=> upgrade react-textarea-autosize dependency to 8.3.2
