mac-s-g/react-json-view

src/js/index.js

Throws a runtime error when the component updates because props is not defined.

Fix reference error `props is not defined`

---

example/example.html
example/example.js
src/html/test-dist.html.template
src/js/components/DataTypes/DataTypes.js
src/js/components/DataTypes/Date.js
src/js/components/VariableEditor.js
src/js/themes/getStyle.js
src/js/themes/styleConstants.js
test/tests/js/components/DataTypes/Date-test.js

added support for dates

---

README.md
docker/debug.sh
example/example.html
example/example.js
package.json
src/html/index.html.template
src/js/components/AddKeyRequest.js
src/js/components/DataTypes/Date.js
src/js/components/DataTypes/Object.js
src/js/components/DataTypes/String.js
src/js/components/VariableEditor.js
src/js/components/VariableMeta.js
src/js/helpers/parseInput.js
src/js/index.js
src/js/stores/ObjectAttributes.js
src/js/themes/base16/rjv-themes.js
src/js/themes/getStyle.js
src/js/themes/styleConstants.js
test/tests/js/components/AddKeyRequest-test.js
test/tests/js/components/DataTypes/Date-test.js
test/tests/js/components/DataTypes/String-test.js
test/tests/js/components/VariableEditor-test.js
test/tests/js/components/VariableMeta-test.js
test/tests/js/helpers/parseInput-test.js

adding the following props:
`onAdd` (function)
`onDelete` (function)
also improved `onEdit` functionality

Add delete nodes

---

README.md
example/example.js
package.json
src/js/components/DataTypes/Object.js
test/tests/js/components/DataTypes/Object-test.js

This allows the user to specify pass an integer value to the `collapsed` prop.  
Use an integer value to collapse at a particular depth.

added integer support to `collapsed` prop

---

Dockerfile
README.md
entrypoints/coverage.sh
entrypoints/debug.sh
entrypoints/install-test-dependencies.sh
entrypoints/test.sh
entrypoints/test_watch.sh
package.json
src/html/index.html.template
webpack.config.js

radium: 63.25 KB (12.8%)
inline-style-prefixer: 56.87 KB (11.5%)
react-tooltip: 49.97 KB (10.1%)
babel-runtime: 39.75 KB (8.01%)
core-js: 36.45 KB (91.7%)
<self>: 3.29 KB (8.28%)
lodash.curry: 35.03 KB (7.06%)
base16: 22.03 KB (4.44%)
bowser: 17.29 KB (3.49%)
clipboard: 15.31 KB (3.09%)
lodash.flow: 11.37 KB (2.29%)
react-icons: 10.49 KB (2.11%)
react-base16-styling: 9.73 KB (1.96%)
events: 8.13 KB (1.64%)
flux: 7.46 KB (1.50%)
react-icon-base: 4.33 KB (0.872%)
prop-types: 2.37 KB (54.9%)
<self>: 1.95 KB (45.1%)
pure-color: 3.45 KB (0.696%)
good-listener: 3.37 KB (0.680%)
prop-types: 3.04 KB (0.612%)
fbjs: 2.65 KB (0.535%)
delegate: 1.82 KB (0.367%)
tiny-emitter: 1.53 KB (0.308%)
classnames: 1.08 KB (0.217%)
select: 1 KB (0.202%)
exenv: 863 B (0.170%)
webpack: 597 B (0.118%) …

Remove react from bundle

---

src/js/index.js
test/tests/js/components/VariableEditor-test.js

This PR fixes #95.
I'm not really sure why the props.src duplication in state and in ObjectAttributes is necessary, instead of just using the props.src directly. I'm also not sure if componentDidUpdate is the right place to update ObjectAttributes but at least it passes all tests. I have also added a test to ensure the fixed behavior.

Fixes #95 Correct current updated_src after an onEdit 

---

dev-server/src/index.js
package.json
src/js/components/DataTypes/Object.js
test/tests/js/components/DataTypes/Object-test.js

empty nodes will default to a collapsed state and ellipsis will not be rendered.

updated behavior rendering behavior for empty objects

---

package.json

- Allows React 16 as a peer dependency

Fix peerDependency warning for React v16

---

src/js/components/DataTypes/Boolean.js

Followup to #128, this PR changes the boolean datatype to show:
```
true/false
```
instead of
```
True/False
```

Lowercase true/false

---

README.md
dev-server/src/index.js
package.json
src/js/components/ArrayGroup.js
src/js/components/DataTypes/Object.js
src/js/components/JsonViewer.js
src/js/components/ObjectName.js
src/js/components/ToggleIcons.js
src/js/components/VariableMeta.js
src/js/index.js
src/js/themes/getStyle.js
src/js/themes/styleConstants.js
test/tests/js/Index-test.js
test/tests/js/components/ArrayGroup-test.js
test/tests/js/components/ObjectName-test.js
test/tests/js/components/ToggleIcons-test.js
test/tests/js/components/VariableMeta-test.js

Hi there! 
I've been using this for a project of mine (fantastic work on this project, it's by far the best react based JSON prettifier I've found). My project deals with pretty large JSON datasets - especially arrays. I found that displaying 200+ array elements all at once was pretty slow to render, so I thought I would introduce a PR to group arrays by count, like so: 
The limit for the group size can be set with the component property `groupArraysAfterLength`. By default, this property is set to false and ignored.
I've coded the initial proof of concept and it appears to be working in the scenarios I've tested so far. You can take a look at it on the dev server at the very last example. 
Before I go further with testing, I wanted to send this over to you to take a look at the …

Support for grouping large arrays

---

webpack/webpack.config-dev.js

Readme Mention to use localhost to run demo but 0.0.0.0 is defined in webpack-dev file. 
With the change in webpack it launches the app correctly with 'npm run dev'

[Small-FIX] Changed devServer host to point to localhost from 0.0.0.0

---

README.md
src/js/components/DataTypes/Object.js
src/js/index.js
test/tests/js/components/DataTypes/Object-test.js

sometimes its nice to be able to tell the renderer that we want the keys sorted. 
This PR adds a prop `sortKeys` that will sort object keys alphabetically.

sort object keys

---

package.json
src/js/index.js

Cancel modal bug

---

src/js/index.js

`ValidationFailure` fails to display default or custom messages.
Following is the screenshot from the dev-server
```
Run the Dev Server
git clone git@github.com:mac-s-g/react-json-view.git && cd react-json-view
npm install --save-dev
npm run dev
Edit any field to 'error'
```
```
npm -v 5.6.0
node -v v9.8.0
react -v 16.4.1
Browser: Chrome: Version 67.0.3396.99 (Official Build) (64-bit)
```
Seems like `validationMessage` state wasn't initialized.

Empty Validation Message Bug

---

README.md
dev-server/src/index.js
index.d.ts
package.json
src/js/components/ObjectKeyModal/AddKeyRequest.js
src/js/index.js

The current behaviour when adding a new key to JSON is to set its value to null. I needed it to be empty string, and I thought other people could benefit to setting the default value to something else. 
For instance if you have a JSON with booleans, you could default new entries to true or false.
The code added is little intrusive to the whole system.
I wasn't sure what testing I could add for it, and I'm happy to make one if given directions.
Also the name of the prop `defaultValue` might be too 'wide' for what it does, any naming suggestions appreciated.

Add a way to set the default value when adding a key to json

---

src/js/index.js

This is a fix for" When the src prop is updated from parent component the edition is  broken" #206

Update glocal src attribute when src prop is updated

---

src/style/scss/global.scss

@mac-s-g Many thanks for this great project. We are successfully using it in production. However, we have identified 2 minor bugs :
- the AddKeyRequest component is masked when the initial JSON is empty and there is another ReactJson component below. So, a good compromise could be to set a min-height on the react-json-view container
- when the value of a key is too long, after a click on it, it displays beyond the container. So, a good fix would be to use the [word-break CSS property](https://css-tricks.com/almanac/properties/w/word-break/)

set default style with min-height & word-bread

---

src/js/helpers/parseInput.js
test/tests/js/helpers/parseInput-test.js

This fixes a bug where small floats (eg. `0.0000002`) would not be detected as floats due to `JSON.parse` converting them to scientific notation (`2e-7`).

Fix bug with small floats and add support for scientific notation

---

README.md
src/js/components/ObjectName.js
src/js/index.js
test/tests/js/components/DataTypes/Object-test.js
test/tests/js/components/ObjectName-test.js

In reference to https://github.com/mac-s-g/react-json-view/pull/171 this adds the ability to disable quotes on key fields. Defaults to `true` to preserve existing behavior.

Add quotesOnKeys option

---

.github/workflows/ci-tests.yml
package-lock.json
package.json

Running tests on CI will help us to review PRs

Add Github actions to run tests on CI

---

.babelrc
package.json

istanbul should only be included as a plugin when `NODE_ENV=test`

remove coverage info from production build

---

src/js/components/DataTypes/Object.js

Just a refresh of this PR based on latest master: https://github.com/mac-s-g/react-json-view/pull/263
Change originally by @clangen-nw
cc: @mac-s-g (I don't seem to be able to assign reviewers)

Don't sort keys if the object is an array.

---

src/js/components/JsonViewer.js
test/tests/js/Index-test.js

Hi @mac-s-g,
This pull request covers the issue #252 where the 'length' property is misinterpreted as the length of an array.
Best,

Fix display issue for objects with length property

---

index.d.ts

missing quotesOnKeys props in TS typings

fix: missing quotesOnKeys props in TS typings

---

src/js/components/JsonViewer.js

If an object has more keys than `groupArraysAfterLength`, then it will be rendered as an Array due to the changes in #336
Fix this logic so only arrays are rendered as arrays.
Fixes #340

Fix "Invalid array length" error
